### ISSUE TITLE
What Happened Recently.... [DO NOT REMOVE]

### ISSUE THREAD

**Issue by githubberguy** [FastFlags/FastFlags-Collective#2]
- NEWS:
Really im still asking how.. I Managed to make the dev of https://github.com/devstacking/Epic-Fast-Flags-List
delete the list..
But WHY?
(edit: they removed the github account, dont know if they got banned or he did it himself)

- CRITICAL REQUEST
since the recent news and the recent critical request from bloxstrap
the owners decided to delete fastflags list
but your wondering why?
![Screenshot 2024-02-23 175657](https://github.com/FastFlags/FastFlags-Collective/assets/145132255/b28f02f8-1f1a-43b4-ae99-286d5a92b547)
Yes ^^ is the CRITICAL request 

- WHY REMOVING FASTFLAGS?
![Screenshot 2024-02-23 175711](https://github.com/FastFlags/FastFlags-Collective/assets/145132255/e8938ea1-2bf2-45f0-9fd4-83e10d01c4ef)
thats why they need to remove it
beacuse fastflags will be no longer editable

THEYRE NULLIFYING IT
so some devbuilds of 2.6.0 (most recent)
no longer have FASTFLAGS..
but some 2.6.0 versions HAS FASTFLAGS

before you delete this list, i didnt ask to remove any lists..
you still can keep these fastflags as long they still work
(yes, yet they didnt drop the update)

**Comment by githubberguy** [comment]
well tho now you wont be able to change fflags, still works JUST FOR NOW, in the next update probably its restricted.

**Comment by joshclark756** [comment]
as of today flags still work

**Comment by 1x4z** [comment]
known

**Comment by d44df016fe28bc8d5974** [comment]
the new github is https://github.com/FastFlags/FastFlags-Collective

**Comment by githubberguy** [comment]
ok
